version: '3'

services:
  symfony-app:
    build:
      context: ./pet-registry-server
    ports:
      - "8000:8000"
  vue-app:
    build:
      context: ./pet-registry-client
    ports:
      - "8080:8080"
    depends_on:
      - symfony-app