controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_v1_pet:
    path: api/v1/pet
    controller: App\Controller\Api\v1\PetController::create
    methods: ['POST']